package game.panelsAndFrames;

import game.Game;

/**
 * These are the functional buttons south of the game view
 *
 * @author JohnA
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    private Game game;
    private int pause;

    public ControlPanel(Game game) {
        initComponents();
        this.game = game;
        pause = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pauseResume = new javax.swing.JButton();
        mainMenu = new javax.swing.JButton();
        skipLevel = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        quit = new javax.swing.JButton();

        jButton4.setText("jButton4");

        jButton6.setText("jButton6");

        setBackground(new java.awt.Color(72, 46, 27));
        setPreferredSize(new java.awt.Dimension(985, 50));

        pauseResume.setBackground(new java.awt.Color(255, 255, 255));
        pauseResume.setText("Pause/Resume");
        pauseResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseResumeActionPerformed(evt);
            }
        });

        mainMenu.setBackground(new java.awt.Color(255, 255, 255));
        mainMenu.setText("Main Menu");
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });

        skipLevel.setBackground(new java.awt.Color(255, 255, 255));
        skipLevel.setText("Skip Level");
        skipLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipLevelActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(pauseResume)
                .addGap(59, 59, 59)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(skipLevel)
                .addGap(60, 60, 60)
                .addComponent(mainMenu)
                .addGap(65, 65, 65)
                .addComponent(quit)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pauseResume)
                    .addComponent(skipLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quit))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pauseResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseResumeActionPerformed
        // Pause TODO button add your handling code here:
        if (pause == 1) {
            if (game.level == 3){
                game.music2.pause();
            } else if (game.level == 4){
                game.america.pause();
            } else {
                game.music1.pause();
            }
            game.getWorld().stop();
            game.timer.stop();
            System.out.println("Game paused");
            pause = 0;
        } else if (pause == 0){
            if (game.level == 3){
                game.music2.resume();
            } else if (game.level == 4){
                game.america.resume();
            } else {
                game.music1.resume();
            }
            game.getWorld().start();
            game.timer.start();
            pause = 1;
            System.out.println("Game resumed");
        }

    }//GEN-LAST:event_pauseResumeActionPerformed

    private void skipLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipLevelActionPerformed
        // Skip Level button TODO add your handling code here:
        game.goNextLevel();
    }//GEN-LAST:event_skipLevelActionPerformed

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        // Quit button TODO add your handling code here:
        game.back();
        game.getPlayer().stopDeadMusic();
        MainMenu.menu.setVisible(true);
        MainMenu.clip.start();
    }//GEN-LAST:event_mainMenuActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // Restart button TODO add your handling code here:
        game.getPlayer().stopDeadMusic();
        game.resetGame();
        game.resetTime();
    }//GEN-LAST:event_resetActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_quitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton mainMenu;
    private javax.swing.JButton pauseResume;
    private javax.swing.JButton quit;
    private javax.swing.JButton reset;
    private javax.swing.JButton skipLevel;
    // End of variables declaration//GEN-END:variables
}
